default_language_version:
  # for mac try using: `python: python` or `python: python3`
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: ["--unsafe"]
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    # isort config is in setup.cfg
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    # flake8 config is in setup.cfg
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0"
    hooks:
      - id: prettier
        types_or:
          [markdown, css, scss, javascript, json, yaml, ts, tsx, jsx, graphql]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.3.0]
  - repo: local
    hooks:
      - id: pre-commit-django-migrations
        name: Check django migrations
        entry: ./scripts/check_migrations.sh
        language: system
        pass_filenames: false
        files: ^.*models\.py$|^.*choices\.py$
  #  - repo: https://github.com/PyCQA/bandit
  #    rev: 1.7.0
  #    hooks:
  #      - id: bandit
  #  - repo: https://github.com/Yelp/detect-secrets
  #    rev: v1.4.0
  #    hooks:
  #      - id: detect-secrets
  #        args: ["--baseline", ".secrets.baseline"]
  #        exclude: ".*tests.*|service-account.test.json|.env.test|.env.example"
  - repo: local
    hooks:
      - id: djhtml
        name: djhtml
        entry: djhtml
        language: python
        types: [html]
        additional_dependencies: [djhtml]
