x-common: &common
  stdin_open: true
  tty: true
  restart: unless-stopped
  networks:
    - bank_management_system

services:
  celery:
    build:
      context: .
      dockerfile: ./Dockerfile.stage
    container_name: bank_management_system-cc01
    restart: unless-stopped
    command: bash -c "celery -A bank_management_system worker -l info"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - .:/code/
    <<: *common

  celery-beat:
    build:
      context: .
      dockerfile: ./Dockerfile.stage
    container_name: bank_management_system-cb01
    restart: unless-stopped
    command: bash -c "celery -A bank_management_system worker -l info --beat --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - django
      - redis
    env_file:
      - .env
    volumes:
      - .:/code/
    <<: *common

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  django:
    build:
      context: .
      dockerfile: ./Dockerfile.stage
    container_name: bank_management_system-dc01
    restart: unless-stopped
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/code
      - bank_management_system_static_volume:/code/static
      - bank_management_system_media_volume:/code/media
    depends_on:
      - postgres
      - redis
    <<: *common

  flower:
    build:
      context: .
      dockerfile: ./Dockerfile.stage
    container_name: bank_management_system-fc01
    command: bash -c "celery -A bank_management_system --broker=redis://${REDIS_URL}/0 flower --url_prefix=flower --basic_auth=${FLOWER_USERNAME}:${FLOWER_PASSWORD}"
    ports:
      - "5555:5555"
    depends_on:
      - celery
    env_file:
      - .env
    volumes:
      - .:/code/
    <<: *common

  nginx:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile
    container_name: bank_management_system-nc01
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/stage/default.conf:/etc/nginx/conf.d/default.conf
      - bank_management_system_static_volume:/code/static
      - bank_management_system_media_volume:/code/media
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - django
      - flower
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    <<: *common

  postgres:
    image: postgres:13.3-buster
    container_name: bank_management_system-pc01
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - bank_management_system_postgres_data:/var/lib/postgresql/data/
    <<: *common

  redis:
    image: redis:6.2-buster
    container_name: bank_management_system-rc01
    restart: unless-stopped
    volumes:
      - bank_management_system_redis_data:/data
    <<: *common

networks:
  bank_management_system:
    driver: bridge

volumes:
  bank_management_system_postgres_data:
  bank_management_system_redis_data:
  bank_management_system_static_volume:
  bank_management_system_media_volume:
