# Generated by Django 5.1.6 on 2025-02-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
