# Generated by Django 5.1.6 on 2025-02-13 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_account_user"),
        ("banks", "0002_rename_branch_bank_branch_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={("user", "bank")},
        ),
    ]
