# Generated by Django 5.1.6 on 2025-02-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_account_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="account",
            unique_together=set(),
        ),
    ]
