# Generated by Django 4.2.16 on 2025-02-18 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0002_rename_branch_bank_branch_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0009_alter_account_bank_alter_account_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_account",
                to="banks.bank",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
